# Generated by Django 5.1.1 on 2024-09-15 13:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('faq', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='faq',
            name='title',
            field=models.CharField(default='Tangerine', max_length=50),
        ),
    ]
